//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aut_user
    {
        public int id { get; set; }
        public string user_aut { get; set; }
        public string password_aut { get; set; }
        public string estado_aut { get; set; }
    }
}
